name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Test on node
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    env:
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Build TypeScript
        run: yarn run build

      - name: Run tests
        run: yarn run test

      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
